theme: jekyll-theme-cayman
title: Learn French Today
description: Simple steps to perfect French
github:
  page2: grammar.html
  page3: vocabulary.html
  page4: listening.html
  page5: reading.html
  page6: homework.html
  
 
