theme: jekyll-theme-cayman
title: Learn English Today
description: Simple steps to perfect English

<p> About me </p>.
I was born in London and grew up in Hertfordshire. My orgins are French, Jamaican and Scottish. I am studying French with Busines Mangement.I have been living in London for 3 years.
If you wish to know more information, the link for my portfolio is <a href="https://hub.qmplus.qmul.ac.uk/view/view.php?profile=ml15258&page=sml209-computers-and-languages-2018-lauren"> visit the link </a>
